### ISSUE TITLE
Option to have Parent.Builder.builder() api

### ISSUE THREAD

**Issue by cwensel** [rookie0peng/builder-generator-plus-v2#3]
I'm migrating from another builder plugin, and I've noticed many build apis have the following signature:

```
Parent.Builder.builder().build();
```

It would be nice to have that as an option so that I don't need to regenerate all my other builders, but this also seems like a common pattern. Unsure of its merits though.

**Comment by rookie0peng** [comment]
Is the **Parent** mean current class or super class ?

**Comment by cwensel** [comment]
Parent is the class the Builder is nested in as an inner class. This is instead of `Parent.builder().build()`

**Comment by rookie0peng** [comment]
Maybe I've understood what you're thinking.

You want the **builder** method inside **Builder** class. Is right?

For example.

`
public class Parent {

    private String a;

    public static Builder builder() {
        return Builder.aParent();
    }

    public String getA() {
        return a;
    }

    public void setA(String a) {
        this.a = a;
    }

    @Override
    public String toString() {
        return "Parent{" +
                "a='" + a + '\'' +
                '}';
    }

    public static final class Builder {
        private String a;

        private Builder() {
        }

        /**
         * builder method inside Builder class 
         */
        public static Builder builder() {
            return Builder.aParent();
        }

        public static Builder aParent() {
            return new Builder();
        }

        public Builder a(String a) {
            this.a = a;
            return this;
        }

        public Parent build() {
            Parent parent = new Parent();
            parent.setA(a);
            return parent;
        }
    }
}
`

And then we can use it like this.
`
    public static void main(String[] args) {
        Parent.Builder.builder().build();
    }
`

**Comment by cwensel** [comment]
Would look like this:

```
public class Parent {
  public static final class Builder {
    public static Builder builder() {
            return new Builder();
        }
  }
  public Parent build() {
            return new Parent(this);
        }
}
```

**Comment by rookie0peng** [comment]
Hello, my friend! This Builder Plugin (2.0.0) has supported customized src class 'builder' method exists or not. Maybe you can try it now.

eg.
![image](https://github.com/rookie0peng/builder-generator-plus-v2/assets/24223066/a129d500-1a81-43ac-8536-6ceb557a28c2)

**Comment by rookie0peng** [comment]
You can customize the 'builder' method name.

![image](https://github.com/rookie0peng/builder-generator-plus-v2/assets/24223066/aa9713ea-d5a9-4773-90ed-5111e2bc3439)

**Comment by cwensel** [comment]
it works great, thanks!
