### ISSUE TITLE
Compatibility with Idea 2023.1

### ISSUE THREAD

**Issue by cwensel** [rookie0peng/builder-generator-plus-v2#4]
Seems there are some compatibility issues.

![image](https://user-images.githubusercontent.com/24684/229628106-cb2b090c-4225-4860-94f5-6cd895653579.png)

**Comment by rookie0peng** [comment]
Ok, i will do it today!

**Comment by rookie0peng** [comment]
I've been so busy lately that I don't have time to develop. However, now I have time  to optimize the plugin. Thanks for your support!
