### ISSUE TITLE
Compatibility with Idea 2023.3

### ISSUE THREAD

**Issue by cwensel** [rookie0peng/builder-generator-plus-v2#8]
Here we are again with the version dependency checks.

![image](https://github.com/rookie0peng/builder-generator-plus-v2/assets/24684/4f74a344-30f4-4277-9959-5cd80a86003c)

**Comment by rookie0peng** [comment]
Ok, i will upgrade it in three days.



---Original---
From: "Chris K ***@***.***&gt;
Date: Tue, Dec 12, 2023 03:51 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rookie0peng/builder-generator-plus-v2] Compatibility with Idea2023.3 (Issue #8)




 
Here we are again with the version dependency checks.
 
image.png (view on web)

**Comment by rookie0peng** [comment]
Okay, the plugin will be approved within two business days.

![image](https://github.com/rookie0peng/builder-generator-plus-v2/assets/24223066/8694279c-a77d-4877-8203-634c366aa155)

**Comment by rookie0peng** [comment]
Hi bro, the plugin has been approved, you can download it from the marketplace.

**Comment by cwensel** [comment]
Excellent thanks!!
